import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig, type Plugin } from "vite";
import routes from "./src/routes.json";

/**
 * Emits the files a static Pages deployment needs around the bundle:
 *
 * - sw.js, with the exact list of hashed assets this build produced, so the
 *   app shell works offline from the first visit after install. Hand-written
 *   rather than Workbox: it is small, and it must never intercept the API.
 * - _redirects, an SPA fallback for known routes only. A blanket `/*` rule
 *   would answer /robots.txt typos and every probe with a 200 app shell;
 *   listing prefixes keeps real 404s real.
 * - 404.html, a copy of the shell served with a 404 status for everything
 *   else, so the page still renders a useful not-found screen.
 */
function pagesArtifacts(): Plugin {
  let outDir = "dist";
  return {
    name: "pacestreak-pages-artifacts",
    apply: "build",
    configResolved(config) {
      outDir = config.build.outDir;
    },
    generateBundle(_options, bundle) {
      const assets = Object.keys(bundle)
        .filter((f) => !f.endsWith(".map") && f !== "index.html")
        .map((f) => `/${f}`);
      const version = Date.now().toString(36);
      const source = readFileSync(resolve(__dirname, "sw/sw.js"), "utf8")
        .replace("__PRECACHE__", JSON.stringify(["/", ...assets, "/manifest.webmanifest", "/icons/icon-192.png", "/icons/icon-512.png"]))
        .replace("__VERSION__", version);
      this.emitFile({ type: "asset", fileName: "sw.js", source });

      const rules = routes.prefixes
        .filter((p) => p !== "/")
        // Rewrite to "/", not "/index.html": Pages answers a request for
        // /index.html with a 308 to /, and applies that to rewrite targets
        // too, so every deep link (a reload, a shared URL) landed on Today.
        .flatMap((p) => [`${p} / 200`, `${p}/* / 200`]);
      this.emitFile({
        type: "asset",
        fileName: "_redirects",
        source: `# Generated by vite.config.ts from src/routes.json. Do not edit.\n${rules.join("\n")}\n`,
      });
    },
    closeBundle() {
      const html = readFileSync(resolve(outDir, "index.html"), "utf8");
      writeFileSync(resolve(outDir, "404.html"), html);
    },
  };
}

export default defineConfig({
  plugins: [react(), tailwindcss(), pagesArtifacts()],
  // Keep the variable name the repository already documented (.env.example).
  envPrefix: "PUBLIC_",
  build: {
    // Load-bearing. Vite inlines assets under 4KB as data: URIs and our CSP
    // has no 'unsafe-inline' - an inlined script is blocked, silently.
    assetsInlineLimit: 0,
    sourcemap: false,
    target: "es2022",
    rollupOptions: {
      output: {
        // Framework code changes a few times a year; app code changes every
        // deploy. Separate chunks let a returning visitor keep the former.
        manualChunks(id: string) {
          if (/node_modules\/(react|react-dom|scheduler|react-router)\//.test(id)) return "react";
          if (id.includes("node_modules/@tanstack/")) return "query";
        },
      },
    },
  },
  server: { port: 5173, strictPort: true },
  test: { environment: "node" },
} as never);
